[package]
name = "ina219"
version = "0.1.0"
edition = "2021"
authors = ["Matt Gleich"]
categories = ["embedded", "no-std"]
description = "Driver for the TI ina219 IC"
license = "MIT"
repository = "https://github.com/gleich/ina219"
readme = "README.md"

[dependencies]
embedded-hal = "0.2.6"
